disabled_rules:
- multiple_closures_with_trailing_closure
line_length:
- 200
nesting:
  type_level:
    warning: 3 --> this means the warning appears if you nest 3 level deep instead of 1
    error: 6
  statement_level:
    warning: 5
    error: 10
